package view;

import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import service.HoaDonChiTietService;
import viewmodel.QLHoaDon;
import viewmodel.QLHoaDonChiTiet;

/**
 *
 * @author admin
 */
public class JPanelHoaDon extends javax.swing.JPanel {

    DefaultTableModel defaultTableModelHoaDon;
    DefaultTableModel defaultTableModelSanPham;
    HoaDonChiTietService hoaDonChiTietService = new HoaDonChiTietService();
    List<QLHoaDonChiTiet> listSanPham = new ArrayList<>();

    public JPanelHoaDon() {
        initComponents();
        String[] tt = {"Tất cả", "Đã thanh toán", "Chưa thanh toán"};
        String[] date = {"Ngày Tạo", "Ngày Thanh Toán"};
        for (String tt1 : tt) {
            cbo_trangthai.addItem(tt1);
        }
        for (String date1 : date) {
            cbo_date.addItem(date1);
        }
        fillTable(hoaDonChiTietService.getListHoaDon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbo_trangthai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sanpham = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cbo_date = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txt_startdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_enddate = new javax.swing.JTextField();
        btn_inhoadon = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1070, 680));
        setPreferredSize(new java.awt.Dimension(1070, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HÓA ĐƠN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Trạng Thái");

        cbo_trangthai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_trangthaiItemStateChanged(evt);
            }
        });

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Tên NV", "Tên KH", "Sđt", "Ngày tạo", "Ngày thanh toán", "Tổng tiền", "Trạng Thái"
            }
        ));
        tbl_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_hoadon);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Sản Phẩm");

        tbl_sanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Giá bán", "Khuyến mãi (%)", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(tbl_sanpham);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày");

        cbo_date.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_dateItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Từ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Đến");

        btn_inhoadon.setBackground(new java.awt.Color(186, 79, 84));
        btn_inhoadon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_inhoadon.setForeground(new java.awt.Color(255, 255, 255));
        btn_inhoadon.setText("In hóa đơn");
        btn_inhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inhoadonActionPerformed(evt);
            }
        });

        btn_timkiem.setBackground(new java.awt.Color(186, 79, 84));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_timkiem)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbo_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbo_date, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(958, 958, 958))
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btn_inhoadon)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_inhoadon)
                .addGap(33, 33, 33))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 1070, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hoadonMouseClicked
        int index = tbl_hoadon.getSelectedRow();
        listSanPham = hoaDonChiTietService.getListHoaDonChiTiet(tbl_hoadon.getValueAt(index, 0).toString());
        fillSanPham(listSanPham);
    }//GEN-LAST:event_tbl_hoadonMouseClicked

    private void btn_inhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inhoadonActionPerformed
        int index = tbl_hoadon.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn để in");
            return;
        }

        String path = "";
        JFileChooser chooser = new JFileChooser("D:\\");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = chooser.showSaveDialog(this);

        if (x == JFileChooser.APPROVE_OPTION) {
            path = chooser.getSelectedFile().getPath();
        }

        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "hoadonchitiet.pdf"));
            doc.open();

            String ma = tbl_hoadon.getValueAt(index, 0).toString();
            String tenKH = tbl_hoadon.getValueAt(index, 2).toString();
            String ngayTao = tbl_hoadon.getValueAt(index, 4).toString();
            String ngayThanhToan = tbl_hoadon.getValueAt(index, 5).toString();
            double tongTien = Double.parseDouble(tbl_hoadon.getValueAt(index, 6).toString());

            PdfPTable tbl3 = new PdfPTable(3);
            PdfPTable tblTenCuaHang = new PdfPTable(1);
            PdfPTable tblLoiCamOn = new PdfPTable(1);
            PdfPTable tblDanhSach = new PdfPTable(2);
            PdfPTable tblTongTien = new PdfPTable(2);

            for (int i = 0; i < tbl_sanpham.getRowCount(); i++) {
                String tenSP = tbl_sanpham.getValueAt(i, 0).toString();
                String soLuong = tbl_sanpham.getValueAt(i, 3).toString();
                String donGia = tbl_sanpham.getValueAt(i, 4).toString();
                PdfPCell cellTenSP = new PdfPCell(new Phrase(tenSP));
                PdfPCell cellDonGia = new PdfPCell(new Phrase(donGia));
                PdfPCell cellSoLuong = new PdfPCell(new Phrase("SL: " + soLuong));
                cellTenSP.setBorderColor(Color.WHITE);
                cellDonGia.setBorderColor(Color.WHITE);
                cellSoLuong.setBorderColor(Color.WHITE);
                cellTenSP.setPaddingLeft(30);
                cellTenSP.setPaddingBottom(10);
                cellDonGia.setPaddingLeft(72);
                cellDonGia.setPaddingBottom(10);
                cellSoLuong.setPaddingLeft(10);
                cellSoLuong.setPaddingBottom(10);
                tbl3.addCell(cellTenSP);
                tbl3.addCell(cellDonGia);
                tbl3.addCell(cellSoLuong);
            }

            PdfPCell cellTitle = new PdfPCell(new Phrase("SEVENT STORE"));
            PdfPCell cellEnd = new PdfPCell(new Phrase("CAM ON QUY KHACH"));
            PdfPCell cellLater = new PdfPCell(new Phrase("HEN GAP LAI!"));
            cellTitle.setBorderColor(Color.WHITE);
            cellEnd.setBorderColor(Color.WHITE);
            cellLater.setBorderColor(Color.WHITE);
            cellTitle.setPaddingBottom(50);
            cellTitle.setPaddingLeft(130);
            tblTenCuaHang.addCell(cellTitle);
            cellEnd.setPaddingTop(50);
            cellEnd.setPaddingLeft(100);
            cellLater.setPaddingTop(10);
            cellLater.setPaddingLeft(120);

            PdfPCell cellMa = new PdfPCell(new Phrase("Ma Hoa Don"));
            PdfPCell cellMa1 = new PdfPCell(new Phrase(ma));
            PdfPCell cellKH = new PdfPCell(new Phrase("Khach Hang"));
            PdfPCell cellKH1 = new PdfPCell(new Phrase(tenKH));
            PdfPCell cellNgayTao = new PdfPCell(new Phrase("Ngay Tao"));
            PdfPCell cellNgayTao1 = new PdfPCell(new Phrase(ngayTao));
            PdfPCell cellNgayThanhToan = new PdfPCell(new Phrase("Ngay Thanh Toan"));
            PdfPCell cellNgayThanhToan1 = new PdfPCell(new Phrase(ngayThanhToan));
            PdfPCell cellVachKe = new PdfPCell(new Phrase("--------------------------------------------"));
            PdfPCell cellVachKe1 = new PdfPCell(new Phrase("--------------------------------------------"));
            PdfPCell cellTongTien = new PdfPCell(new Phrase("Tong Tien"));

            PdfPCell cellKhuyenMai = new PdfPCell(new Phrase("Khuyen Mai"));

            cellMa.setBorderColor(Color.WHITE);
            cellMa1.setBorderColor(Color.WHITE);
            cellMa.setPaddingBottom(10);
            cellMa.setPaddingLeft(30);
            cellKH.setBorderColor(Color.WHITE);
            cellKH1.setBorderColor(Color.WHITE);
            cellKH.setPaddingBottom(10);
            cellKH.setPaddingLeft(30);
            cellNgayTao.setBorderColor(Color.WHITE);
            cellNgayTao1.setBorderColor(Color.WHITE);
            cellNgayTao.setPaddingBottom(10);
            cellNgayTao.setPaddingLeft(30);
            cellNgayThanhToan.setBorderColor(Color.WHITE);
            cellNgayThanhToan1.setBorderColor(Color.WHITE);
            cellNgayThanhToan.setPaddingBottom(10);
            cellNgayThanhToan.setPaddingLeft(30);
            cellVachKe.setBorderColor(Color.WHITE);
            cellVachKe1.setBorderColor(Color.WHITE);
            cellVachKe.setPaddingBottom(10);
            cellVachKe.setPaddingLeft(30);

            cellKhuyenMai.setBorderColor(Color.WHITE);
            cellKhuyenMai.setPaddingBottom(10);
            cellKhuyenMai.setPaddingLeft(30);

            tblDanhSach.addCell(cellMa);
            tblDanhSach.addCell(cellMa1);
            tblDanhSach.addCell(cellKH);
            tblDanhSach.addCell(cellKH1);
            tblDanhSach.addCell(cellNgayTao);
            tblDanhSach.addCell(cellNgayTao1);
            tblDanhSach.addCell(cellNgayThanhToan);
            tblDanhSach.addCell(cellNgayThanhToan1);
            tblDanhSach.addCell(cellVachKe);
            tblDanhSach.addCell(cellVachKe1);

            tblTongTien.addCell(cellKhuyenMai);
            int khuyenMai = 0;
            for (int i = 0; i < 1; i++) {
                khuyenMai = Integer.parseInt(tbl_sanpham.getValueAt(i, 2).toString());
                PdfPCell cellKhuyenMai1 = new PdfPCell(new Phrase(khuyenMai + "%"));
                cellKhuyenMai1.setBorderColor(Color.WHITE);
                tblTongTien.addCell(cellKhuyenMai1);
            }

            double giaTri = (tongTien * khuyenMai) / 100;
            double tienPhaiTra = tongTien - giaTri;
            PdfPCell cellTongTien1 = new PdfPCell(new Phrase(String.valueOf(tienPhaiTra)));
            cellTongTien.setBorderColor(Color.WHITE);
            cellTongTien1.setBorderColor(Color.WHITE);
            cellTongTien.setPaddingBottom(10);
            cellTongTien.setPaddingLeft(30);

            tblTongTien.addCell(cellTongTien);
            tblTongTien.addCell(cellTongTien1);
            tblLoiCamOn.addCell(cellEnd);
            tblLoiCamOn.addCell(cellLater);

            doc.add(tblTenCuaHang);
            doc.add(tblDanhSach);
            doc.add(tbl3);
            doc.add(tblTongTien);
            doc.add(tblLoiCamOn);

        } catch (FileNotFoundException | DocumentException ex) {
            ex.getMessage();
        }
        doc.close();
    }//GEN-LAST:event_btn_inhoadonActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (txt_timkiem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tìm kiếm không được trống");
            txt_timkiem.requestFocus();
        } else {
            fillTable(hoaDonChiTietService.filterHoaDonByNameNV(txt_timkiem.getText()));
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void cbo_trangthaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_trangthaiItemStateChanged
        int tt = cbo_trangthai.getSelectedIndex();
        switch (tt) {
            case 0 ->
                fillTable(hoaDonChiTietService.getListHoaDon());
            case 1 ->
                fillTable(hoaDonChiTietService.filterHoaDonByTrangThai(1));
            case 2 ->
                fillTable(hoaDonChiTietService.filterHoaDonByTrangThai(0));
            default -> {
            }
        }
    }//GEN-LAST:event_cbo_trangthaiItemStateChanged

    private void cbo_dateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_dateItemStateChanged
        String ngay = (String) cbo_date.getSelectedItem();
        String ngay1 = ngay.equalsIgnoreCase("Ngày Tạo") ? "NgayTao":"NgayThanhToan";
        fillTable(hoaDonChiTietService.filterHoaDonByNameAndDate(txt_timkiem.getText(), ngay1, txt_startdate.getText(), txt_enddate.getText()));
    }//GEN-LAST:event_cbo_dateItemStateChanged

    private void fillTable(List<QLHoaDon> list) {
        defaultTableModelHoaDon = (DefaultTableModel) tbl_hoadon.getModel();
        defaultTableModelHoaDon.setRowCount(0);
        for (QLHoaDon ql : list) {
            String tt = ql.getTrangThai() == 1 ? "Đã thanh toán" : "Chưa thanh toán";
            defaultTableModelHoaDon.addRow(new Object[]{ql.getMaHD(), ql.getTenNV(), ql.getTenKH(), ql.getSdt(), ql.getNgayTao(), ql.getNgayThanhToan(), ql.getTongTien(), tt});
        }
    }

    private void fillSanPham(List<QLHoaDonChiTiet> list) {
        defaultTableModelSanPham = (DefaultTableModel) tbl_sanpham.getModel();
        defaultTableModelSanPham.setRowCount(0);
        for (QLHoaDonChiTiet ql : list) {
            defaultTableModelSanPham.addRow(new Object[]{ql.getTenSP(), ql.getGiaBan(), ql.getGiaTri(), ql.getSoLuong(), ql.getDonGia()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inhoadon;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JComboBox<String> cbo_date;
    private javax.swing.JComboBox<String> cbo_trangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_hoadon;
    private javax.swing.JTable tbl_sanpham;
    private javax.swing.JTextField txt_enddate;
    private javax.swing.JTextField txt_startdate;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
