/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainmodel.NhanVien;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.NhanVienService;

/**
 *
 * @author admin
 */
public class JPanelNhanVien extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel;
    NhanVienService nhanVienService = new NhanVienService();
    int index = 0;

    public JPanelNhanVien() {
        initComponents();
        fillTable(nhanVienService.getListNV());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nhanvien = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btn_first = new javax.swing.JButton();
        btn_predious = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ngaysinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdo_dilam = new javax.swing.JRadioButton();
        rdo_nghiviec = new javax.swing.JRadioButton();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1070, 680));

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addContainerGap(933, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        txt_timkiem.setBorder(null);
        txt_timkiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 22));

        tbl_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Mã ", "Tên", "Ngày sinh", "Giới tính", "SDT", "Địa chỉ", "Trạng thái"
            }
        ));
        tbl_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nhanvien);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 628, 329));

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, 220, 5));

        btn_first.setBackground(new java.awt.Color(186, 79, 84));
        btn_first.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/first25px.png"))); // NOI18N
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });
        jPanel2.add(btn_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 429, -1, -1));

        btn_predious.setBackground(new java.awt.Color(186, 79, 84));
        btn_predious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/predious25px.png"))); // NOI18N
        btn_predious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prediousActionPerformed(evt);
            }
        });
        jPanel2.add(btn_predious, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 429, -1, -1));

        btn_next.setBackground(new java.awt.Color(186, 79, 84));
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next25px.png"))); // NOI18N
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel2.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 429, -1, -1));

        btn_last.setBackground(new java.awt.Color(186, 79, 84));
        btn_last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/last25px.png"))); // NOI18N
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });
        jPanel2.add(btn_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 429, -1, -1));

        btn_timkiem.setBackground(new java.awt.Color(186, 79, 84));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search25px.png"))); // NOI18N
        btn_timkiem.setText("Tìm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel2.add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 87, 32));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        txt_ma.setBorder(null);
        jPanel3.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 160, 20));

        txt_ten.setBorder(null);
        jPanel3.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 160, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ngày sinh");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txt_ngaysinh.setBorder(null);
        jPanel3.add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 160, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Giới tính");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        buttonGroup1.add(rdo_nam);
        rdo_nam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdo_nam.setSelected(true);
        rdo_nam.setText("Nam");
        jPanel3.add(rdo_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        buttonGroup1.add(rdo_nu);
        rdo_nu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdo_nu.setText("Nữ");
        jPanel3.add(rdo_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("SDT");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txt_sdt.setBorder(null);
        jPanel3.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Địa chỉ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        txt_diachi.setBorder(null);
        jPanel3.add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 160, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Trạng thái");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        buttonGroup2.add(rdo_dilam);
        rdo_dilam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdo_dilam.setSelected(true);
        rdo_dilam.setText("Đi làm");
        jPanel3.add(rdo_dilam, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        buttonGroup2.add(rdo_nghiviec);
        rdo_nghiviec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdo_nghiviec.setText("Nghỉ việc");
        jPanel3.add(rdo_nghiviec, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        btn_them.setBackground(new java.awt.Color(186, 79, 84));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add20px.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 87, 32));

        btn_sua.setBackground(new java.awt.Color(186, 79, 84));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit20px.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 87, 32));

        btn_xoa.setBackground(new java.awt.Color(186, 79, 84));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete20px.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 87, 32));

        btn_lammoi.setBackground(new java.awt.Color(186, 79, 84));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear20px.png"))); // NOI18N
        btn_lammoi.setText("Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel3.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 87, 32));

        jSeparator2.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, 10));

        jSeparator3.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 160, 10));

        jSeparator4.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 10));

        jSeparator5.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 10));

        jSeparator6.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);
        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, nhanVienService.addNV(getField()));
            fillTable(nhanVienService.getListNV());
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?", "Sửa", JOptionPane.YES_NO_OPTION);
        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, nhanVienService.updateNV(getField()));
            fillTable(nhanVienService.getListNV());
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, nhanVienService.deleteNV(txt_ma.getText()));
            fillTable(nhanVienService.getListNV());
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        txt_ma.setText("");
        txt_ten.setText("");
        txt_ngaysinh.setText("");
        txt_sdt.setText("");
        txt_diachi.setText("");
        rdo_nam.setSelected(true);
        rdo_dilam.setSelected(true);
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        if (nhanVienService.getListNV().size() != 0) {
            index = 0;
        }
        fillField(index);
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_prediousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prediousActionPerformed
        if (nhanVienService.getListNV().size() != 0) {
            if (index == 0) {
                index = nhanVienService.getListNV().size() - 1;
            } else {
                index--;
            }
        }
        fillField(index);
    }//GEN-LAST:event_btn_prediousActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        if (nhanVienService.getListNV().size() != 0) {
            if (index == nhanVienService.getListNV().size() - 1) {
                index = 0;
            } else {
                index++;
            }
        }
        fillField(index);
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        if (nhanVienService.getListNV().size() != 0) {
            index = nhanVienService.getListNV().size() - 1;
        }
        fillField(index);
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        fillTable(nhanVienService.getListNVByMa(txt_timkiem.getText()));
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void tbl_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanvienMouseClicked
        int a = tbl_nhanvien.getSelectedRow();

        txt_ma.setText(tbl_nhanvien.getValueAt(a, 1).toString());
        txt_ten.setText(tbl_nhanvien.getValueAt(a, 2).toString());
        txt_ngaysinh.setText(tbl_nhanvien.getValueAt(a, 3).toString());
        txt_sdt.setText(tbl_nhanvien.getValueAt(a, 5).toString());
        txt_diachi.setText(tbl_nhanvien.getValueAt(a, 6).toString());
        if (tbl_nhanvien.getValueAt(a, 4).toString().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }

        if (tbl_nhanvien.getValueAt(a, 7).toString().equalsIgnoreCase("Đi làm")) {
            rdo_dilam.setSelected(true);
        } else {
            rdo_nghiviec.setSelected(false);
        }
    }//GEN-LAST:event_tbl_nhanvienMouseClicked

    private void fillTable(List<NhanVien> list) {
        defaultTableModel = (DefaultTableModel) tbl_nhanvien.getModel();
        defaultTableModel.setRowCount(0);
        for (NhanVien nv : list) {
            String tt = nv.getTrangThai() == 1 ? "Đi làm" : "Nghỉ việc";
            defaultTableModel.addRow(new Object[]{nv.getId(), nv.getMa(), nv.getTen(), nv.getNgaySinh(),
                nv.getGioiTinh(), nv.getSDT(), nv.getDiaChi(), tt});
        }
    }

    private void fillField(int index) {
        txt_ma.setText(tbl_nhanvien.getValueAt(index, 1).toString());
        txt_ten.setText(tbl_nhanvien.getValueAt(index, 2).toString());
        txt_ngaysinh.setText(tbl_nhanvien.getValueAt(index, 3).toString());
        txt_sdt.setText(tbl_nhanvien.getValueAt(index, 5).toString());
        txt_diachi.setText(tbl_nhanvien.getValueAt(index, 6).toString());
        if (tbl_nhanvien.getValueAt(index, 4).toString().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }

        if (tbl_nhanvien.getValueAt(index, 7).toString().equalsIgnoreCase("Đi làm")) {
            rdo_dilam.setSelected(true);
        } else {
            rdo_nghiviec.setSelected(false);
        }
    }
    
    private NhanVien getField() {
        NhanVien nhanVien = new NhanVien();
        nhanVien.setMa(txt_ma.getText());
        nhanVien.setTen(txt_ten.getText());
        nhanVien.setNgaySinh(txt_ngaysinh.getText());
        nhanVien.setSDT(txt_sdt.getText());
        nhanVien.setDiaChi(txt_diachi.getText());
        if(rdo_nam.isSelected()) {
            nhanVien.setGioiTinh("Nam");
        } else {
            nhanVien.setGioiTinh("Nữ");
        }
        
        if(rdo_dilam.isSelected()) {
            nhanVien.setTrangThai(1);
        } else {
            nhanVien.setTrangThai(0);
        }
        return nhanVien;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_predious;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton rdo_dilam;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nghiviec;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_nhanvien;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
