/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainmodel.KhachHang;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.KhachHangService;

/**
 *
 * @author admin
 */
public class JPanelKhachHang extends javax.swing.JPanel {

    DefaultTableModel defaultTableModel;
    KhachHangService khachHangService = new KhachHangService();
    int index = 0;
    private static final Pattern DATE_PATTERN = Pattern.compile("^((2000|2400|2800|(19|2[0-9])(0[48]|[2468][048]|[13579][26]))-02-29)$"
            + "|^(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))$"
            + "|^(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))$"
            + "|^(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30))$");

    public JPanelKhachHang() {
        initComponents();
        fillTable(khachHangService.getListKhachHang());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_ngaysinh = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachhang = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lammoi = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_predious = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        chk_trangthai = new javax.swing.JCheckBox();
        btn_timkiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_diachi = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1070, 680));
        setPreferredSize(new java.awt.Dimension(1070, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Mã khách hàng:");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, -1, -1));

        txt_ma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ma.setBorder(null);
        txt_ma.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(txt_ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 49, 174, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Tên khách hàng");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 119, -1, -1));

        txt_ten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ten.setBorder(null);
        jPanel3.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 151, 174, -1));

        txt_ngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_ngaysinh.setBorder(null);
        jPanel3.add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 236, 174, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Ngày sinh");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Giới Tính");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 19, -1, -1));

        rdo_nam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_nam);
        rdo_nam.setSelected(true);
        rdo_nam.setText("Nam");
        jPanel3.add(rdo_nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 49, 67, -1));

        rdo_nu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("Nữ");
        jPanel3.add(rdo_nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 49, 67, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 119, -1, -1));

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sdt.setBorder(null);
        jPanel3.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 151, 174, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Địa chỉ");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 206, -1, -1));

        txt_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiem.setBorder(null);
        jPanel3.add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 174, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Tìm kiếm");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 19, -1, -1));

        tbl_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ma", "Ten", "NgaySinh", "GioiTinh", "Sdt", "DiaChi", "TrangThai"
            }
        ));
        tbl_khachhang.setFocusable(false);
        tbl_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachhang);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 663, 207));

        jSeparator1.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 72, 174, 12));

        jSeparator2.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 173, 174, 12));

        jSeparator3.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 258, 174, 10));

        jSeparator4.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 173, 174, 10));

        jSeparator6.setForeground(new java.awt.Color(186, 79, 84));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 74, 174, 10));

        btn_them.setBackground(new java.awt.Color(186, 79, 84));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add20px.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 87, 32));

        btn_sua.setBackground(new java.awt.Color(186, 79, 84));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit20px.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 87, 32));

        btn_xoa.setBackground(new java.awt.Color(186, 79, 84));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete20px.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 87, 32));

        btn_lammoi.setBackground(new java.awt.Color(186, 79, 84));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear20px.png"))); // NOI18N
        btn_lammoi.setText("Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel3.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 87, 32));

        btn_first.setBackground(new java.awt.Color(186, 79, 84));
        btn_first.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/first25px.png"))); // NOI18N
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });
        jPanel3.add(btn_first, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        btn_predious.setBackground(new java.awt.Color(186, 79, 84));
        btn_predious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/predious25px.png"))); // NOI18N
        btn_predious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prediousActionPerformed(evt);
            }
        });
        jPanel3.add(btn_predious, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        btn_next.setBackground(new java.awt.Color(186, 79, 84));
        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next25px.png"))); // NOI18N
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        jPanel3.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, -1, -1));

        btn_last.setBackground(new java.awt.Color(186, 79, 84));
        btn_last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/last25px.png"))); // NOI18N
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });
        jPanel3.add(btn_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, -1, -1));

        chk_trangthai.setText("Trạng thái");
        jPanel3.add(chk_trangthai, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 51, -1, -1));

        btn_timkiem.setBackground(new java.awt.Color(186, 79, 84));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search25px.png"))); // NOI18N
        btn_timkiem.setText("Tìm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        jPanel3.add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, -1, -1));

        txt_diachi.setColumns(20);
        txt_diachi.setRows(5);
        jScrollPane2.setViewportView(txt_diachi);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 236, -1, 70));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 618));

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        if (checkValidate()) {
            int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?", "Thêm", JOptionPane.YES_NO_OPTION);
            if (cf == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, khachHangService.insert(getInput()));
                fillTable(khachHangService.getListKhachHang());
                clearField();
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?", "Sửa", JOptionPane.YES_NO_OPTION);
        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, khachHangService.update(getInput()));
            fillTable(khachHangService.getListKhachHang());
            clearField();
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        int cf = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (cf == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, khachHangService.delete(txt_ma.getText()));
            fillTable(khachHangService.getListKhachHang());
            clearField();
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        clearField();
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        fillTable(khachHangService.getListKhachHang());
        if (!khachHangService.getListKhachHang().isEmpty()) {
            index = 0;
        }
        fillField(index);
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_prediousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prediousActionPerformed
        fillTable(khachHangService.getListKhachHang());
        if (!khachHangService.getListKhachHang().isEmpty()) {
            if (index == 0) {
                index = khachHangService.getListKhachHang().size() - 1;
            } else {
                index--;
            }
        }
        fillField(index);
    }//GEN-LAST:event_btn_prediousActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        fillTable(khachHangService.getListKhachHang());
        if (!khachHangService.getListKhachHang().isEmpty()) {
            if (index == khachHangService.getListKhachHang().size() - 1) {
                index = 0;
            } else {
                index++;
            }
        }
        fillField(index);
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        fillTable(khachHangService.getListKhachHang());
        int index = tbl_khachhang.getSelectedRow();
        if (!khachHangService.getListKhachHang().isEmpty()) {
            index = khachHangService.getListKhachHang().size() - 1;
        }
        fillField(index);
    }//GEN-LAST:event_btn_lastActionPerformed

    private void tbl_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachhangMouseClicked
        int a = tbl_khachhang.getSelectedRow();

        txt_ma.setText(tbl_khachhang.getValueAt(a, 1).toString());
        txt_ten.setText(tbl_khachhang.getValueAt(a, 2).toString());
        txt_ngaysinh.setText(tbl_khachhang.getValueAt(a, 3).toString());
        txt_sdt.setText(tbl_khachhang.getValueAt(a, 5).toString());
        txt_diachi.setText(tbl_khachhang.getValueAt(a, 6).toString());
        if (tbl_khachhang.getValueAt(a, 4).toString().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }

        if (tbl_khachhang.getValueAt(a, 7).toString().equalsIgnoreCase("Còn")) {
            chk_trangthai.setSelected(true);
        } else {
            chk_trangthai.setSelected(false);
        }
    }//GEN-LAST:event_tbl_khachhangMouseClicked

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        if (txt_timkiem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên để tìm kiếm");
            return;
        }
        fillTable(khachHangService.getListKHByMa(txt_timkiem.getText()));
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void fillTable(List<KhachHang> list) {
        defaultTableModel = (DefaultTableModel) tbl_khachhang.getModel();
        defaultTableModel.setRowCount(0);
        for (KhachHang kh : list) {
            String tt = kh.getTrangThai() == 1 ? "Còn" : "Không";
            defaultTableModel.addRow(new Object[]{kh.getId(), kh.getMa(), kh.getTen(), kh.getNgaySinh(),
                kh.getGioiTinh(), kh.getsDT(), kh.getDiaChi(), tt});
        }
    }

    private KhachHang getInput() {
        KhachHang khachHang = new KhachHang();
        khachHang.setMa(txt_ma.getText().trim());
        khachHang.setTen(txt_ten.getText());
        khachHang.setNgaySinh(txt_ngaysinh.getText().trim());
        if (rdo_nam.isSelected()) {
            khachHang.setGioiTinh("Nam");
        } else {
            khachHang.setGioiTinh("Nữ");
        }
        khachHang.setsDT(txt_sdt.getText().trim());
        khachHang.setDiaChi(txt_diachi.getText());
        if (chk_trangthai.isSelected()) {
            khachHang.setTrangThai(1);
        } else {
            khachHang.setTrangThai(0);
        }
        return khachHang;
    }

    private void fillField(int index) {
        txt_ma.setText(tbl_khachhang.getValueAt(index, 1).toString());
        txt_ten.setText(tbl_khachhang.getValueAt(index, 2).toString());
        txt_ngaysinh.setText(tbl_khachhang.getValueAt(index, 3).toString());
        txt_sdt.setText(tbl_khachhang.getValueAt(index, 5).toString());
        txt_diachi.setText(tbl_khachhang.getValueAt(index, 6).toString());
        if (tbl_khachhang.getValueAt(index, 4).toString().equalsIgnoreCase("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }

        if (tbl_khachhang.getValueAt(index, 7).toString().equals("Còn")) {
            chk_trangthai.setSelected(true);
        } else {
            chk_trangthai.setSelected(false);
        }
    }

    private void clearField() {
        txt_ma.setText("");
        txt_ten.setText("");
        txt_ngaysinh.setText("");
        txt_diachi.setText("");
        txt_sdt.setText("");
        chk_trangthai.setSelected(false);
        txt_timkiem.setText("");
    }

    private boolean matches(String date) {
        return DATE_PATTERN.matcher(date).matches();
    }

    private boolean checkValidate() {
        Pattern p = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
        Matcher ma = p.matcher(txt_ma.getText());
        Matcher ten = p.matcher(txt_ten.getText());

        if (txt_ma.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã không được trống");
            txt_ma.requestFocus();
            return false;
        } else if (ma.find()) {
            JOptionPane.showMessageDialog(this, "Mã không được chứa ký tự đặc biệt");
            txt_ma.requestFocus();
            return false;
        }

        if (checkMa(txt_ma.getText()) == 1) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng đã tồn tại");
            txt_ma.requestFocus();
            return false;
        }

        if (txt_ten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên khách hàng không được trống");
            txt_ten.requestFocus();
            return false;
        } else if (ten.find()) {
            JOptionPane.showMessageDialog(this, "Tên không được chứa ký tự đặc biệt");
            txt_ma.requestFocus();
            return false;
        }

        if (txt_ngaysinh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không được trống");
            txt_ngaysinh.requestFocus();
            return false;
        } else if (!matches(txt_ngaysinh.getText())) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không đúng định dạng");
            txt_ngaysinh.requestFocus();
            return false;
        }

        if (txt_sdt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được trống");
            txt_sdt.requestFocus();
            return false;
        } else if (!txt_sdt.getText().matches("0[0-9]{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng");
            txt_sdt.requestFocus();
            return false;
        }

        if (txt_diachi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được trống");
            txt_diachi.requestFocus();
            return false;
        }
        return true;
    }

    private int checkMa(String ma) {
        for (int i = 0; i < khachHangService.getListKhachHang().size(); i++) {
            KhachHang get = khachHangService.getListKhachHang().get(i);
            if (get.getMa().trim().equalsIgnoreCase(ma)) {
                return 1;
            }
        }
        return 2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_predious;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_trangthai;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tbl_khachhang;
    private javax.swing.JTextArea txt_diachi;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
