/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainmodel.CPU;
import domainmodel.Hang;
import domainmodel.ManHinh;
import domainmodel.MauSac;
import domainmodel.OCung;
import domainmodel.RAM;
import domainmodel.SanPham;
import domainmodel.VGA;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.CPUService;
import service.HangService;
import service.ManHinhService;
import service.MauSacService;
import service.OcungService;
import service.RAMService;
import service.SanPhamService;
import service.VGAService;
import viewmodel.SanPhamViewMD;

/**
 *
 * @author quyen
 */
public class JPanelSanPham extends javax.swing.JPanel {

    HangService hS = new HangService();
    OcungService ocS = new OcungService();
    RAMService rS = new RAMService();
    ManHinhService mhS = new ManHinhService();
    VGAService vS = new VGAService();
    CPUService cS = new CPUService();
    MauSacService msS = new MauSacService();
    SanPhamService spS = new SanPhamService();
    List<SanPhamViewMD> listSPV = new ArrayList<>();
    List<SanPham> listSP = new ArrayList<>();
    public JPanelSanPham() {
        initComponents();
        List<Hang> listH = hS.getListH();
        cboHang.setModel(new DefaultComboBoxModel(listH.toArray()));
        List<CPU> listC = cS.getListCPU();
        cboCPU.setModel(new DefaultComboBoxModel(listC.toArray()));
        List<RAM> listR = rS.getListRAM();
        cboRam.setModel(new DefaultComboBoxModel(listR.toArray()));
        List<OCung> listO = ocS.getListO();
        cboOcung.setModel(new DefaultComboBoxModel(listO.toArray()));
        List<VGA> listV = vS.getListV();
        cboVGA.setModel(new DefaultComboBoxModel(listV.toArray()));
        List<ManHinh> listMH = mhS.getListM();
        cboManHinh.setModel(new DefaultComboBoxModel(listMH.toArray()));
        List<MauSac> listMS = msS.getListMS();
        cboMauSac.setModel(new DefaultComboBoxModel(listMS.toArray()));

        fillTB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboSeri = new javax.swing.JComboBox<>();
        cboCPU = new javax.swing.JComboBox<>();
        cboRam = new javax.swing.JComboBox<>();
        cboOcung = new javax.swing.JComboBox<>();
        cboHang = new javax.swing.JComboBox<>();
        cboVGA = new javax.swing.JComboBox<>();
        cboManHinh = new javax.swing.JComboBox<>();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_vga = new javax.swing.JButton();
        btn_hang = new javax.swing.JButton();
        btn_cpu = new javax.swing.JButton();
        btn_ram = new javax.swing.JButton();
        btn_ocung = new javax.swing.JButton();
        btn_serial = new javax.swing.JButton();
        btn_mausac = new javax.swing.JButton();
        btn_manhinh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_gianhap = new javax.swing.JTextField();
        txt_giaban = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_lammoi = new javax.swing.JButton();
        txtMa = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtSLTon = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(186, 79, 84));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Sản phẩm");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setBorder(null);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 20));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Màu Sắc", "Hãng", "RAM", "CPU", "Ổ cứng", "VGA", "Màn Hình", "Số lượng tồn", "Giá Nhập", "Giá Bán"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 60, 660, 300));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 10));

        jButton1.setBackground(new java.awt.Color(186, 79, 84));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 376));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VGA");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 32, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RAM");
        jLabel5.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ổ cứng");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CPU");
        jLabel7.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel7.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 32, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Serial");
        jLabel8.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel8.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Màn hình");
        jLabel9.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel9.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 60, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Màu sắc");
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel10.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel10.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 60, -1));

        jPanel4.add(cboSeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 130, -1));

        jPanel4.add(cboCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, -1));

        jPanel4.add(cboRam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 130, -1));

        jPanel4.add(cboOcung, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 130, -1));

        jPanel4.add(cboHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, -1));

        jPanel4.add(cboVGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        jPanel4.add(cboManHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, -1));

        jPanel4.add(cboMauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hãng");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(40, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 20));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 32, -1));

        btn_vga.setBackground(new java.awt.Color(186, 79, 84));
        btn_vga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_vga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vgaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_vga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 28));

        btn_hang.setBackground(new java.awt.Color(186, 79, 84));
        btn_hang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_hang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hangActionPerformed(evt);
            }
        });
        jPanel4.add(btn_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 28));

        btn_cpu.setBackground(new java.awt.Color(186, 79, 84));
        btn_cpu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cpuActionPerformed(evt);
            }
        });
        jPanel4.add(btn_cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 130, 28));

        btn_ram.setBackground(new java.awt.Color(186, 79, 84));
        btn_ram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ramActionPerformed(evt);
            }
        });
        jPanel4.add(btn_ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 130, 28));

        btn_ocung.setBackground(new java.awt.Color(186, 79, 84));
        btn_ocung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_ocung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocungActionPerformed(evt);
            }
        });
        jPanel4.add(btn_ocung, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 130, 28));

        btn_serial.setBackground(new java.awt.Color(186, 79, 84));
        btn_serial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serialActionPerformed(evt);
            }
        });
        jPanel4.add(btn_serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 130, 28));

        btn_mausac.setBackground(new java.awt.Color(186, 79, 84));
        btn_mausac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_mausac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mausacActionPerformed(evt);
            }
        });
        jPanel4.add(btn_mausac, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 28));

        btn_manhinh.setBackground(new java.awt.Color(186, 79, 84));
        btn_manhinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit3.png"))); // NOI18N
        btn_manhinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manhinhActionPerformed(evt);
            }
        });
        jPanel4.add(btn_manhinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 130, 28));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 670, 190));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Giá bán");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Mã sản phẩm");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Số lượng tồn");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 20));

        txt_gianhap.setBorder(null);
        jPanel5.add(txt_gianhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 20));

        txt_giaban.setBorder(null);
        jPanel5.add(txt_giaban, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Giá nhập");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/aR.png"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 30, 25));

        btn_them.setBackground(new java.awt.Color(186, 79, 84));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add20px.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel5.add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 87, 32));

        btn_sua.setBackground(new java.awt.Color(186, 79, 84));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit20px.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 87, 32));

        btn_xoa.setBackground(new java.awt.Color(186, 79, 84));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete20px.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel5.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 87, 32));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 10));

        btn_lammoi.setBackground(new java.awt.Color(186, 79, 84));
        btn_lammoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_lammoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear20px.png"))); // NOI18N
        btn_lammoi.setText("Mới");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel5.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 87, 32));

        txtMa.setBorder(null);
        jPanel5.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 20));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 10));

        txtSLTon.setBorder(null);
        jPanel5.add(txtSLTon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, 20));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 10));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Tên sản phẩm");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 80, 20));

        txt_ten.setBorder(null);
        jPanel5.add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 120, 20));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, 10));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 350, 580));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1070, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_hangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hangActionPerformed
        CRUDhang hang = new CRUDhang();
        hang.setVisible(true);
    }//GEN-LAST:event_btn_hangActionPerformed

    private void btn_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cpuActionPerformed
        CRUDcpu cpu = new CRUDcpu();
        cpu.setVisible(true);
    }//GEN-LAST:event_btn_cpuActionPerformed

    private void btn_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ramActionPerformed
        CRUDram ram = new CRUDram();
        ram.setVisible(true);
    }//GEN-LAST:event_btn_ramActionPerformed

    private void btn_ocungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocungActionPerformed
        CRUDocung ocung = new CRUDocung();
        ocung.setVisible(true);
    }//GEN-LAST:event_btn_ocungActionPerformed

    private void btn_vgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vgaActionPerformed
        CRUDvga vga = new CRUDvga();
        vga.setVisible(true);
    }//GEN-LAST:event_btn_vgaActionPerformed

    private void btn_manhinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manhinhActionPerformed
        CRUDmanhinh manhinh = new CRUDmanhinh();
        manhinh.setVisible(true);
    }//GEN-LAST:event_btn_manhinhActionPerformed

    private void btn_mausacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mausacActionPerformed
        CRUDmausac mausac = new CRUDmausac();
        mausac.setVisible(true);
    }//GEN-LAST:event_btn_mausacActionPerformed

    private void btn_serialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serialActionPerformed
        CRUDserial serial = new CRUDserial();
        serial.setVisible(true);
    }//GEN-LAST:event_btn_serialActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        addSP();
        fillTB();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        updateSP();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        deleteSP();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        txtMa.setText("");
        txt_ten.setText("");
        txtSLTon.setText("");
        txt_giaban.setText("");
        txt_gianhap.setText("");
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int index = tblSanPham.getSelectedRow();
        mouseClickTB(index);
    }//GEN-LAST:event_tblSanPhamMouseClicked

    public void fillTB() {
        listSPV = spS.getListSPV();
        DefaultTableModel mol = (DefaultTableModel) tblSanPham.getModel();
        mol.setRowCount(0);
        for (SanPhamViewMD sp : listSPV) {
            mol.addRow(new Object[]{sp.getMa(), sp.getTen(), sp.getIdMauSac(), sp.getIdHang(), sp.getIdRam(), sp.getIdCpu(),
                sp.getIdOCung(), sp.getIdVga(), sp.getIdManHinh(), sp.getSLTon(), sp.getGiaNhap(), sp.getGiaBan()});
        }
        tblSanPham.setModel(mol);
        if (tblSanPham.getRowCount() > 0) {
            mouseClickTB(0);
            tblSanPham.setRowSelectionInterval(0, 0);
        }

    }

    public void mouseClickTB(int index) {
        listSPV = spS.getListSPV();
        SanPhamViewMD sp = listSPV.get(index);
        txtMa.setText(sp.getMa());
        txt_ten.setText(sp.getTen());
        txt_gianhap.setText(sp.getGiaNhap() + "");
        txt_giaban.setText(sp.getGiaBan() + "");
        txtSLTon.setText(sp.getSLTon() + "");

    }

    public void addSP() {
        Hang h = (Hang) cboHang.getSelectedItem();
        CPU cpu = (CPU) cboCPU.getSelectedItem();
        RAM ram = (RAM) cboRam.getSelectedItem();
        OCung oc = (OCung) cboOcung.getSelectedItem();
        ManHinh mh = (ManHinh) cboManHinh.getSelectedItem();
        VGA vga = (VGA) cboVGA.getSelectedItem();
        MauSac ms = (MauSac) cboMauSac.getSelectedItem();

        SanPham sp = new SanPham();
        sp.setIdHang(h.getId());
        sp.setIdCpu(cpu.getId());
        sp.setIdRam(ram.getId());
        sp.setIdOCung(oc.getId());
        sp.setIdVga(vga.getId());
        sp.setIdManHinh(mh.getId());
        sp.setIdMauSac(ms.getId());
        sp.setMa(txtMa.getText());
        sp.setTen(txtMa.getText());
        sp.setGiaNhap(Double.valueOf(txt_gianhap.getText()));
        sp.setGiaBan(Double.valueOf(txt_giaban.getText()));
        sp.setSLTon(Integer.parseInt(txtSLTon.getText()));
        boolean rs = spS.insert(sp);
        if (rs == true) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
        }

    }

    public void updateSP() {
        Hang h = (Hang) cboHang.getSelectedItem();
        CPU cpu = (CPU) cboCPU.getSelectedItem();
        RAM ram = (RAM) cboRam.getSelectedItem();
        OCung oc = (OCung) cboOcung.getSelectedItem();
        ManHinh mh = (ManHinh) cboManHinh.getSelectedItem();
        VGA vga = (VGA) cboVGA.getSelectedItem();
        MauSac ms = (MauSac) cboMauSac.getSelectedItem();
        String ma = txtMa.getText();
        String ten = txtMa.getText();
        double giaN = Double.parseDouble(txt_gianhap.getText());
        double giaB = Double.parseDouble(txt_giaban.getText());
        int sl = Integer.parseInt(txtSLTon.getText());
        int index = tblSanPham.getSelectedRow();
        listSP = spS.getListSP();
        SanPham sp = listSP.get(index);
        SanPham spCheck = spS.getSP(txtMa.getText());
        if (spCheck == null) {
            sp = new SanPham(sp.getId(), ms.getId(), h.getId(), ram.getId(), cpu.getId(),
                    oc.getId(), vga.getId(), mh.getId(), ma, ten, sl, giaN, giaB, 0);
            boolean rs = spS.update(sp);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            fillTB();
        } else if (sp.getMa().equals(txtMa.getText())) {
            sp = new SanPham(sp.getId(), ms.getId(), h.getId(), ram.getId(), cpu.getId(),
                    oc.getId(), vga.getId(), mh.getId(), ma, ten, sl, giaN, giaB, 0);
            boolean rs = spS.update(sp);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            fillTB();
        } else {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
        }
    }

    private void deleteSP() {
        int index = tblSanPham.getSelectedRow();
        SanPhamViewMD sp = listSPV.get(index);
        boolean result = spS.delete(sp);
        if (result == true) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            fillTB();
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cpu;
    private javax.swing.JButton btn_hang;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_manhinh;
    private javax.swing.JButton btn_mausac;
    private javax.swing.JButton btn_ocung;
    private javax.swing.JButton btn_ram;
    private javax.swing.JButton btn_serial;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_vga;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cboCPU;
    private javax.swing.JComboBox<String> cboHang;
    private javax.swing.JComboBox<String> cboManHinh;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboOcung;
    private javax.swing.JComboBox<String> cboRam;
    private javax.swing.JComboBox<String> cboSeri;
    private javax.swing.JComboBox<String> cboVGA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSLTon;
    private javax.swing.JTextField txt_giaban;
    private javax.swing.JTextField txt_gianhap;
    private javax.swing.JTextField txt_ten;
    // End of variables declaration//GEN-END:variables
}
