/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JLabel;

/**
 *
 * @author quyen
 */
public class mainForm extends javax.swing.JFrame {

    public mainForm() {
        initComponents();
        date();
        new Thread() {
            public void run() {
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss a");
                    lbl_time.setText(dateFormat.format(date));
                }
            }
        }.start();

    }

    public mainForm(String username) {
        initComponents();
        txt_user.setText(username);
        date();
        new Thread() {
            public void run() {
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss a");
                    lbl_time.setText(dateFormat.format(date));
                }
            }
        }.start();
    }

    private void date() {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        LocalDateTime dateTime = LocalDateTime.now();
        lbl_date.setText(dateTimeFormatter.format(dateTime));
    }

    private void showForm(Component component) {
        pnlCard1.removeAll();
        pnlCard1.add(component);
        pnlCard1.revalidate();
        pnlCard1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_sell = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        btn_product = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_staff = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btn_customer = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btn_report = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_promotion = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btn_receipt = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        pnlCard3 = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pnlCard4 = new javax.swing.JPanel();
        pnlCard5 = new javax.swing.JPanel();
        pnlCard6 = new javax.swing.JPanel();
        pnlCard7 = new javax.swing.JPanel();
        pnlCard8 = new javax.swing.JPanel();
        pnlCard2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainForm"); // NOI18N
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(186, 79, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(186, 79, 84));
        btn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home.setName(""); // NOI18N
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu2.png"))); // NOI18N
        btn_home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);
        btn_home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trang Chủ");
        btn_home.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 50));

        btn_sell.setBackground(new java.awt.Color(186, 79, 84));
        btn_sell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_sell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_sellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_sellMouseExited(evt);
            }
        });
        btn_sell.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cart.png"))); // NOI18N
        btn_sell.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 36, 30));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        btn_sell.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Bán hàng");
        btn_sell.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 50));

        btn_product.setBackground(new java.awt.Color(186, 79, 84));
        btn_product.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_productMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_productMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_productMouseExited(evt);
            }
        });
        btn_product.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/laptop.png"))); // NOI18N
        btn_product.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 36, 30));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        btn_product.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sản Phẩm");
        btn_product.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 180, 50));

        btn_staff.setBackground(new java.awt.Color(186, 79, 84));
        btn_staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_staffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_staffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_staffMouseExited(evt);
            }
        });
        btn_staff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/staff2.png"))); // NOI18N
        btn_staff.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 40, 30));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        btn_staff.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nhân Viên");
        btn_staff.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 180, 50));

        btn_customer.setBackground(new java.awt.Color(186, 79, 84));
        btn_customer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_customerMouseExited(evt);
            }
        });
        btn_customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/client.png"))); // NOI18N
        btn_customer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 36, 30));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        btn_customer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Khách Hàng");
        btn_customer.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 50));

        btn_report.setBackground(new java.awt.Color(186, 79, 84));
        btn_report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reportMouseExited(evt);
            }
        });
        btn_report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report2.png"))); // NOI18N
        btn_report.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 36, 30));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        btn_report.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Doanh Thu");
        btn_report.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 180, 50));

        btn_promotion.setBackground(new java.awt.Color(186, 79, 84));
        btn_promotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_promotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_promotionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_promotionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_promotionMouseExited(evt);
            }
        });
        btn_promotion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/promotion.png"))); // NOI18N
        btn_promotion.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 36, 30));

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        btn_promotion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Khuyến Mãi");
        btn_promotion.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_promotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 50));

        btn_receipt.setBackground(new java.awt.Color(186, 79, 84));
        btn_receipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_receiptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_receiptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_receiptMouseExited(evt);
            }
        });
        btn_receipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receipt.png"))); // NOI18N
        btn_receipt.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 36, 30));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        btn_receipt.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 50));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Hóa Đơn");
        btn_receipt.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel2.add(btn_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 180, 50));

        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jelly_band_64px.png"))); // NOI18N
        lbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_userMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 64, 64));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("SevenT Store");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 680));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circleRed.png"))); // NOI18N
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setOpaque(true);
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        jPanel9.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circleGreen.png"))); // NOI18N
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 20));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/circleYel.png"))); // NOI18N
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 20, 20));

        lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 51, 51));
        jPanel9.add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 80, 20));

        lbl_date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 51, 51));
        jPanel9.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 90, 20));

        txt_user.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 51, 51));
        jPanel9.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 80, 20));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 20));

        pnlCard1.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard1.setMinimumSize(new java.awt.Dimension(1070, 680));
        pnlCard1.setLayout(new java.awt.BorderLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hinh-anh-loi-chao-welcome_094125267 (1).png"))); // NOI18N
        pnlCard1.add(jLabel22, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(pnlCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard4.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard5.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard6.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard7.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard8.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        pnlCard2.setOpaque(false);
        pnlCard2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(pnlCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1070, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        bar(jLabel2);
        showForm(new JPanelTrangChu());
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        btn_home.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        btn_home.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_sellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseClicked
        bar(jLabel5);
        showForm(new JPanelBanHang(txt_user.getText()));
    }//GEN-LAST:event_btn_sellMouseClicked

    private void btn_sellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseEntered
        btn_sell.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_sellMouseEntered

    private void btn_sellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseExited
        btn_sell.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_sellMouseExited

    private void btn_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productMouseClicked
        bar(jLabel8);
        showForm(new JPanelSanPham());
    }//GEN-LAST:event_btn_productMouseClicked

    private void btn_productMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productMouseEntered
        btn_product.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_productMouseEntered

    private void btn_productMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_productMouseExited
        btn_product.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_productMouseExited

    private void btn_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffMouseClicked
        bar(jLabel11);
        showForm(new JPanelNhanVien());
    }//GEN-LAST:event_btn_staffMouseClicked

    private void btn_staffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffMouseEntered
        btn_staff.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_staffMouseEntered

    private void btn_staffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_staffMouseExited
        btn_staff.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_staffMouseExited

    private void btn_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseClicked
        bar(jLabel14);
        showForm(new JPanelKhachHang());
    }//GEN-LAST:event_btn_customerMouseClicked

    private void btn_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseEntered
        btn_customer.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_customerMouseEntered

    private void btn_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseExited
        btn_customer.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_customerMouseExited

    private void btn_promotionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promotionMouseClicked
        bar(jLabel21);
        showForm(new JPanelKhuyenMai());
    }//GEN-LAST:event_btn_promotionMouseClicked

    private void btn_promotionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promotionMouseEntered
        btn_promotion.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_promotionMouseEntered

    private void btn_promotionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_promotionMouseExited
        btn_promotion.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_promotionMouseExited

    private void btn_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseClicked
        bar(jLabel17);
        showForm(new JPanelDoanhThu());
    }//GEN-LAST:event_btn_reportMouseClicked

    private void btn_reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseEntered
        btn_report.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_reportMouseEntered

    private void btn_reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseExited
        btn_report.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_reportMouseExited

    private void btn_receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_receiptMouseClicked
        bar(jLabel15);
        showForm(new JPanelHoaDon());
    }//GEN-LAST:event_btn_receiptMouseClicked

    private void btn_receiptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_receiptMouseEntered
        btn_receipt.setBackground(Color.decode("#002488"));
    }//GEN-LAST:event_btn_receiptMouseEntered

    private void btn_receiptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_receiptMouseExited
        btn_receipt.setBackground(Color.decode("#BA4F54"));
    }//GEN-LAST:event_btn_receiptMouseExited

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void lbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_userMouseClicked
        DoiMatKhau dmk = new DoiMatKhau(txt_user.getText());
        dmk.setVisible(true);
    }//GEN-LAST:event_lbl_userMouseClicked

    public void bar(JLabel lb) {
        jLabel2.setOpaque(false);
        jLabel5.setOpaque(false);
        jLabel8.setOpaque(false);
        jLabel11.setOpaque(false);
        jLabel14.setOpaque(false);
        jLabel15.setOpaque(false);
        jLabel17.setOpaque(false);
        jLabel21.setOpaque(false);
        lb.setOpaque(true);
        jPanel2.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_customer;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_product;
    private javax.swing.JPanel btn_promotion;
    private javax.swing.JPanel btn_receipt;
    private javax.swing.JPanel btn_report;
    private javax.swing.JPanel btn_sell;
    private javax.swing.JPanel btn_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCard4;
    private javax.swing.JPanel pnlCard5;
    private javax.swing.JPanel pnlCard6;
    private javax.swing.JPanel pnlCard7;
    private javax.swing.JPanel pnlCard8;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
